version: '3.12'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app           # Syncs the entire project directory
      - ./db.sqlite3:/app/db.sqlite3  # Persistent storage for SQLite database
    env_file:
      - .env
