# Generated by Django 5.1.3 on 2024-12-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_check", "0003_rename_recommended_job_result_recommended_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="skills",
            field=models.ManyToManyField(to="risk_check.skill"),
        ),
    ]
