# Generated by Django 5.2.17 on 2026-10-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk_check", "0004_alter_post_skills_alter_result_matched_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="result",
            name="analysis",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="post",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="post_skills", to="risk_check.skill"
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="matched_skills",
            field=models.ManyToManyField(
                blank=True, related_name="matched_skills", to="risk_check.skill"
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="risk_index",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=5, null=True
            ),
        ),
    ]
