name: Deploy Django to DigitalOcean App Platform via Docker

on:
  push:
    branches:
      - main  # Trigger deployment on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from GitHub
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx for multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t nyeinchan/secureer:doapp .

    # Step 5: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push nyeinchan/secureer:doapp

    # Step 6: Deploy to DigitalOcean App Platform using the DigitalOcean API
    - name: Deploy to DigitalOcean App Platform
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.DO_ACCESS_TOKEN }}" \
          -d '{
                "spec": {
                  "name": "'${{ secrets.DO_APP_NAME }}'",
                  "services": [
                    {
                      "name": "web",
                      "image": "nyeinchan/secureer:doapp",
                      "envs": [
                        {
                          "key": "DJANGO_SECRET_KEY",
                          "value": "django-insecure-u8_nf*9t9raz!8+!!1w=qih)w7b_wx&f2626pb+!xo(sfu#wy%"
                        },
                        {
                          "key": "DEBUG",
                          "value": "false"
                        }
                      ]
                    }
                  ]
                }
              }' \
          https://api.digitalocean.com/v2/apps/${{ secrets.DO_APP_NAME }}/deploy
