name: Deploy Django to DigitalOcean App Platform via Docker

on:
  push:
    branches:
      - main  # Trigger deployment on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Generate a unique tag for the Docker image
    - name: Set Docker image tag
      id: vars
      run: echo "TAG=git-${{ github.sha }}" >> $GITHUB_ENV

    # Step 5: Build and tag Docker image
    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/secureer:${{ env.TAG }} .
        docker tag your-dockerhub-username/secureer:${{ env.TAG }} nyeinchan/secureer:latest

    # Step 6: Push both tags to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push nyeinchan/secureer:${{ env.TAG }}
        docker push nyeinchan/secureer:latest

    # Step 7: Trigger redeploy on DigitalOcean App Platform
    - name: Trigger DigitalOcean App Platform Redeploy
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.DO_ACCESS_TOKEN }}" \
          -d '{
                "components": [
                  {
                    "name": "web",  # Replace "web" with your actual component name
                    "source": {
                      "image": {
                        "registry": "docker.io",
                        "repository": "nyeinchan/secureer",
                        "tag": "'${{ env.TAG }}'"
                      }
                    }
                  }
                ]
              }' \
          https://api.digitalocean.com/v2/apps/${{ secrets.DO_APP_NAME }}/deployments \
        -v  # Verbose flag for debugging

    # Step 8: Log API Response (for debugging)
    - name: Log DigitalOcean API Response
      run: echo "Redeploy request completed. Check DigitalOcean for updates."
