name: Deploy to DigitalOcean App Platform

on:
  push:
    branches:
      - main  # Trigger deployment on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and tag Docker image
    - name: Build Docker Image
      run: |
        docker build -t nyeinchan/secureer:${{ github.sha }} .
        docker tag nyeinchan/secureer:${{ github.sha }} nyeinchan/secureer:latest

    # Step 5: Push Docker image to Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker push nyeinchan/secureer:${{ github.sha }}
        docker push nyeinchan/secureer:latest

    # Step 6: Trigger App Platform Redeployment
    - name: Trigger Redeployment on DigitalOcean
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.DO_ACCESS_TOKEN }}" \
          -d '{
                "components": [
                  {
                    "name": "secureer",  # Replace with your component name if it's not "web"
                    "source": {
                      "image": {
                        "registry": "docker.io",
                        "repository": "nyeinchan/secureer",
                        "tag": "latest"
                      }
                    }
                  }
                ]
              }' \
          https://api.digitalocean.com/v2/apps/${{ secrets.DO_APP_NAME }}/deployments

    # Step 7: Run migrations on the deployed container
    - name: Run Database Migrations
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.DO_ACCESS_TOKEN }}" \
          -d '{
                "components": [
                  {
                    "name": "web",
                    "run_command": "python manage.py migrate --noinput"
                  }
                ]
              }' \
          https://api.digitalocean.com/v2/apps/${{ secrets.DO_APP_NAME }}/components/web/commands
