name: Deploy Django to DigitalOcean App Platform via Docker

on:
  push:
    branches:
      - main  # Trigger deployment on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from GitHub
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx for multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image with the 'latest' tag
    - name: Build Docker image
      run: |
        docker build -t nyeinchan/secureer:doapp .

    # Step 5: Push Docker image to Docker Hub with the 'latest' tag
    - name: Push Docker image to Docker Hub
      run: |
        docker push nyeinchan/secureer:doapp

    # Step 6: Trigger a redeploy on DigitalOcean App Platform
    - name: Trigger DigitalOcean App Platform Redeploy
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.DO_ACCESS_TOKEN }}" \
          -d '{
                "components": [
                  {
                    "name": "nyeinchan-secureer",
                    "source": {
                      "image": {
                        "registry": "docker.io",
                        "repository": "nyeinchan/secureer",
                        "tag": "doapp"
                      }
                    }
                  }
                ]
              }' \
          https://api.digitalocean.com/v2/apps/${{ secrets.DO_APP_NAME }}/deployments
